version: "3"
services:

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432

  polecat:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:test@db/postgres
      POLECAT_JWT_SECRET: secret
    depends_on:
      - db
